# See https://pyup.io/docs/bot/config/

# Search for requirement files
# search: True

# Update all packages
# allowed: all, insecure, False
# update: all

# Dependency pinning
# pin: True

requirements:
  - docs/constraints.txt:
      update: all
      pin: True
  - docs/requirements.txt:
      update: False
      pin: False

# Default Branch
default: main

# Update schedule
schedule: "every week"

# Add a label to pull requests
label_prs: update

# Assign users to pull requests
assignees:
 - veit
 - cusyio

# Branch pre-fix
branch_prefix: pyup-

# Allow to close stale PRs
close_prs: True
